exports = [
    //row 0
    {name: 'nop', code: 0x00},
    {name: 'ld bc, ....', code: 0x01},
    {name: 'ld (bc),a', code: 0x02},
    {name: 'inc bc', code: 0x03},
    {name: 'inc b', code: 0x04},
    {name: 'inc c', code: 0x05},
    {name: 'ld b,..', code: 0x06},
    {name: 'rcla', code: 0x07},
    {name: 'ex af,af\'', code: 0x08},
    {name: 'add hl,bc', code: 0x09},
    {name: 'ls a,(bc)', code: 0x0a},
    {name: 'dec bc', code: 0x0b},
    {name: 'inc c', code: 0x0c},
    {name: 'dec c', code: 0x0d},
    {name: 'ld c,..', code: 0x0e},
    {name: 'rrca', code: 0x0f},
    //row 1
    {name: 'djnz ..', code: 0x10},
    {name: 'ld de,....', code: 0x11},
    {name: 'ld (de),a', code: 0x12},
    {name: 'inc de', code: 0x13},
    {name: 'inc d', code: 0x14},
    {name: 'dec d', code: 0x15},
    {name: 'ld d,..', code: 0x16},
    {name: 'rla', code: 0x17},
    {name: 'jr ..', code: 0x18},
    {name: 'add hl,de', code: 0x19},
    {name: 'ld a,(de)', code: 0x1a},
    {name: 'dec de', code: 0x1b},
    {name: 'inc e', code: 0x1c},
    {name: 'dec e', code: 0x1d},
    {name: 'ld e,..', code: 0x1e},
    {name: 'rra', code: 0x1f},
    //row 2
    {name: 'jr nz,..', code: 0x20},
    {name: 'ld hl,....', code: 0x21},
    {name: 'ld (....),hl', code: 0x22},
    {name: 'inc hl', code: 0x23},
    {name: 'inc h', code: 0x24},
    {name: 'dec h', code: 0x25},
    {name: 'ld h,..', code: 0x26},
    {name: 'daa', code: 0x27},
    {name: 'jr z,..', code: 0x28},
    {name: 'add hl,hl', code: 0x29},
    {name: 'ld hl,(....)', code: 0x2a},
    {name: 'dec hl', code: 0x2b},
    {name: 'inc l', code: 0x2c},
    {name: 'dec l', code: 0x2d},
    {name: 'ld l,..', code: 0x2e},
    {name: 'cpl', code: 0x2f},
    //row 3
    {name: 'jr nc,..', code: 0x30},
    {name: 'ld sp,....', code: 0x31},
    {name: 'ld (....),a', code: 0x32},
    {name: 'inc sp', code: 0x33},
    {name: 'inc (hl)', code: 0x34},
    {name: 'dec (hl)', code: 0x35},
    {name: 'ld (hl),..', code: 0x36},
    {name: 'scf', code: 0x37},
    {name: 'jr c,..', code: 0x38},
    {name: 'add hl,sp', code: 0x39},
    {name: 'ld a,(....)', code: 0x3a},
    {name: 'dec sp', code: 0x3b},
    {name: 'inc a', code: 0x3c},
    {name: 'dec a', code: 0x3d},
    {name: 'ld a,..', code: 0x3e},
    {name: 'ccf', code: 0x3f},
    //row 4
    {name: 'ld b,b', code: 0x40},
    {name: 'ld b,c', code: 0x41},
    {name: 'ld b,d', code: 0x42},
    {name: 'ld b,e', code: 0x43},
    {name: 'ld b,h', code: 0x44},
    {name: 'ld b,l', code: 0x45},
    {name: 'ld b,(hl)', code: 0x46},
    {name: 'ld b,a', code: 0x47},
    {name: 'ld c,b', code: 0x48},
    {name: 'ld c,c', code: 0x49},
    {name: 'ld c,d', code: 0x4a},
    {name: 'ld c,e', code: 0x4b},
    {name: 'ld c,h', code: 0x4c},
    {name: 'ld c,l', code: 0x4d},
    {name: 'ld c,(hl)', code: 0x4e},
    {name: 'ld c,a', code: 0x4f},
    //row 5
    {name: 'ld d,b', code: 0x50},
    {name: 'ld d,c', code: 0x51},
    {name: 'ld d,d', code: 0x52},
    {name: 'ld d,e', code: 0x53},
    {name: 'ld d,h', code: 0x54},
    {name: 'ld d,l', code: 0x55},
    {name: 'ld d,(hl)', code: 0x56},
    {name: 'ld d,a', code: 0x57},
    {name: 'ld e,b', code: 0x58},
    {name: 'ld e,c', code: 0x59},
    {name: 'ld e,d', code: 0x5a},
    {name: 'ld e,e', code: 0x5b},
    {name: 'ld e,h', code: 0x5c},
    {name: 'ld e,l', code: 0x5d},
    {name: 'ld e,(hl)', code: 0x5e},
    {name: 'ld e,a', code: 0x5f},
    //row 6
    {name: 'ld h,b', code: 0x60},
    {name: 'ld h,c', code: 0x61},
    {name: 'ld h,d', code: 0x62},
    {name: 'ld h,e', code: 0x63},
    {name: 'ld h,h', code: 0x64},
    {name: 'ld h,l', code: 0x65},
    {name: 'ld h,(hl)', code: 0x66},
    {name: 'ld h,a', code: 0x67},
    {name: 'ld l,b', code: 0x68},
    {name: 'ld l,c', code: 0x69},
    {name: 'ld l,d', code: 0x6a},
    {name: 'ld l,e', code: 0x6b},
    {name: 'ld l,h', code: 0x6c},
    {name: 'ld l,l', code: 0x6d},
    {name: 'ld l,(hl)', code: 0x6e},
    {name: 'ld l,a', code: 0x6f},
    //row 7
    {name: 'ld (hl),b', code: 0x70},
    {name: 'ld (hl),c', code: 0x71},
    {name: 'ld (hl),d', code: 0x72},
    {name: 'ld (hl),e', code: 0x73},
    {name: 'ld (hl),h', code: 0x74},
    {name: 'ld (hl),l', code: 0x75},
    {name: 'halt', code: 0x76},
    {name: 'ld (hl),a', code: 0x77},
    {name: 'ld a,b', code: 0x78},
    {name: 'ld a,c', code: 0x79},
    {name: 'ld a,d', code: 0x7a},
    {name: 'ld a,e', code: 0x7b},
    {name: 'ld a,h', code: 0x7c},
    {name: 'ld a,l', code: 0x7d},
    {name: 'ld a,(hl)', code: 0x7e},
    {name: 'ld a,a', code: 0x7f},
    //row 8
    {name: 'add a,b', code: 0x80},
    {name: 'add a,c', code: 0x81},
    {name: 'add a,d', code: 0x82},
    {name: 'add a,e', code: 0x83},
    {name: 'add a,h', code: 0x84},
    {name: 'add a,l', code: 0x85},
    {name: 'add a,(hl)', code: 0x86},
    {name: 'add a,a', code: 0x87},
    {name: 'adc a,b', code: 0x88},
    {name: 'adc a,c', code: 0x89},
    {name: 'adc a,d', code: 0x8a},
    {name: 'adc a,e', code: 0x8b},
    {name: 'adc a,h', code: 0x8c},
    {name: 'adc a,l', code: 0x8d},
    {name: 'adc a,(hl)', code: 0x8e},
    {name: 'adc a,a', code: 0x8f},
    //row 9
    {name: 'sub b', code: 0x90},
    {name: 'sub c', code: 0x91},
    {name: 'sub d', code: 0x92},
    {name: 'sub e', code: 0x93},
    {name: 'sub h', code: 0x94},
    {name: 'sub l', code: 0x95},
    {name: 'sub (hl)', code: 0x96},
    {name: 'sub a', code: 0x97},
    {name: 'sbc a,b', code: 0x98},
    {name: 'sbc a,c', code: 0x99},
    {name: 'sbc a,d', code: 0x9a},
    {name: 'sbc a,e', code: 0x9b},
    {name: 'sbc a,h', code: 0x9c},
    {name: 'sbc a,l', code: 0x9d},
    {name: 'sbc a,(hl)', code: 0x9e},
    {name: 'sbc a,a', code: 0x9f},
    //row a
    {name: 'and b', code: 0xa0},
    {name: 'and c', code: 0xa1},
    {name: 'and d', code: 0xa2},
    {name: 'and e', code: 0xa3},
    {name: 'and h', code: 0xa4},
    {name: 'and l', code: 0xa5},
    {name: 'and (hl)', code: 0xa6},
    {name: 'and a', code: 0xa7},
    {name: 'xor b', code: 0xa8},
    {name: 'xor c', code: 0xa9},
    {name: 'xor d', code: 0xaa},
    {name: 'xor e', code: 0xab},
    {name: 'xor h', code: 0xac},
    {name: 'xor l', code: 0xad},
    {name: 'xor (hl)', code: 0xae},
    {name: 'xor a', code: 0xaf},
    //row b
    {name: 'or b', code: 0xb0},
    {name: 'or c', code: 0xb1},
    {name: 'or d', code: 0xb2},
    {name: 'or e', code: 0xb3},
    {name: 'or h', code: 0xb4},
    {name: 'or l', code: 0xb5},
    {name: 'or (hl)', code: 0xb6},
    {name: 'or a', code: 0xb7},
    {name: 'cp b', code: 0xb8},
    {name: 'cp c', code: 0xb9},
    {name: 'cp d', code: 0xba},
    {name: 'cp e', code: 0xbb},
    {name: 'cp h', code: 0xbc},
    {name: 'cp l', code: 0xbd},
    {name: 'cp (hl)', code: 0xbe},
    {name: 'cp a', code: 0xbf},
    //row c
    {name: 'ret nz', code: 0xc0},
    {name: 'pop bc', code: 0xc1},
    {name: 'jp nz,....', code: 0xc2},
    {name: 'jp ....', code: 0xc3},
    {name: 'call nz,....', code: 0xc4},
    {name: 'push bc', code: 0xc5},
    {name: 'add a,..', code: 0xc6},
    {name: 'rst 00h', code: 0xc7},
    {name: 'ret z', code: 0xc8},
    {name: 'ret', code: 0xc9},
    {name: 'jp z,....', code: 0xca},

    {name: 'call z,....', code: 0xcc},
    {name: 'call ....', code: 0xcd},
    {name: 'adc a,..', code: 0xce},
    {name: 'rst 08h', code: 0xcf},
    //row d
    {name: 'ret nc', code: 0xd0},
    {name: 'pop de', code: 0xd1},
    {name: 'jp nc,....', code: 0xd2},
    {name: 'out (..),a', code: 0xd3},
    {name: 'call nc,....', code: 0xd4},
    {name: 'push de', code: 0xd5},
    {name: 'sub ..', code: 0xd6},
    {name: 'rst 10h', code: 0xd7},
    {name: 'ret c', code: 0xd8},
    {name: 'exx', code: 0xd9},
    {name: 'jp c,....', code: 0xda},
    {name: 'in a,(..)', code: 0xdb},
    {name: 'call c,....', code: 0xdc},

    {name: 'sbc a,..', code: 0xde},
    {name: 'rst 18h', code: 0xdf},
    //row e
    {name: 'ret po', code: 0xe0},
    {name: 'pop hl', code: 0xe1},
    {name: 'jp po,....', code: 0xe2},
    {name: 'ex (sp),hl', code: 0xe3},
    {name: 'call po,....', code: 0xe4},
    {name: 'push hl', code: 0xe5},
    {name: 'and ..', code: 0xe6},
    {name: 'rst 20h', code: 0xe7},
    {name: 'ret pe', code: 0xe8},
    {name: 'jp (hl)', code: 0xe9},
    {name: 'jp pe,....', code: 0xea},
    {name: 'ex de,hl', code: 0xeb},
    {name: 'call pe,....', code: 0xec},

    {name: 'xor *', code: 0xee},
    {name: 'rst 28h', code: 0xef},

    //row f
    {name: 'ret p', code: 0xf0},
    {name: 'pop af', code: 0xf1},
    {name: 'jp p,....', code: 0xf2},
    {name: 'di', code: 0xf3},
    {name: 'call p,....', code: 0xf4},
    {name: 'push af', code: 0xf5},
    {name: 'or ..', code: 0xf6},
    {name: 'rst 30h', code: 0xf7},
    {name: 'ret m', code: 0xf8},
    {name: 'ld sp,hl', code: 0xf9},
    {name: 'jp m,....', code: 0xfa},
    {name: 'ei', code: 0xfb},
    {name: 'call m,....', code: 0xfc},

    {name: 'cp *', code: 0xfe},
    {name: 'rst 38h', code: 0xff},
]
